hgate/urls.py
from django.conf.urls.defaults import *
from app.views.index import index
from app.views.repo import repo, hgweb
from app.views.usersv import user, user_index
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
import settings

urlpatterns = patterns('',
    url(r'^$', index, name='index'),
    url(r'repo/(?P<repo_path>.*)', repo, name='repository'),
    url(r'hgweb/?$', hgweb, name='hgweb'),
    url(r'users/?$', user_index, name='users_index'),
    url(r'users/(?P<action>[^/]+)/(?P<login>.*)', user, name='users'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

hgate/app/forms.py
import os
import re
from django import forms
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _
from hgate.app import modhg
from hgate.app.modhg import repository
from hgate.app.modhg.HGWeb import HGWeb
from hgate.app.modhg.repository import RepositoryException
from hgate.app.views.common import prepare_path
import modhg.usersb as users
from django.conf import settings

class FileHashForm(forms.Form):
    file_hash = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, file_hash="", *args, **kwargs):
        super(FileHashForm, self).__init__(*args, **kwargs)
        self.fields['file_hash'].widget.attrs['value'] = file_hash

    def clean(self):
        old_hash = self.cleaned_data['file_hash']
        new_hash = self.fields['file_hash'].widget.attrs['value']
        if old_hash != new_hash:
            self.data = self.data.copy() # make QueryDict mutable
            self.data['file_hash'] = new_hash
            raise forms.ValidationError(_("Configuration file was changed, please try again."))
        return self.cleaned_data

class DeleteGroupForm(FileHashForm):
    def __init__(self, file_hash, *args, **kwargs):
        super(DeleteGroupForm, self).__init__(file_hash, *args, **kwargs)


    def delete_group(self, request, groups):
        name = request.POST["group_name"]
        is_collection = request.POST["is_collection"]
        delete_content = request.POST['delete_content']
        path = dict(groups)[name]
        try:
            modhg.repository.delete_group(path, name, is_collection == 'True', delete_content == 'True')
            messages.success(request, _("Group '%s' was deleted successfully.") % name)
        except modhg.repository.RepositoryException as e:
            messages.warning(request, unicode(e))
        return HttpResponseRedirect(reverse('index'))

class RepositoryForm(FileHashForm):
    allow_read = forms.CharField(label=_("allow_read"), initial=None, required=False) #, widget=forms.TextInput(attrs={'readonly':'readonly'})
    allow_push = forms.CharField(label=_("allow_push"), initial=None, required=False)
    deny_read = forms.CharField(label=_("deny_read"), initial=None, required=False)
    deny_push = forms.CharField(label=_("deny_push"), initial=None, required=False)
    style = forms.CharField(label=_("style"), initial=None, required=False)
    allow_archive = forms.CharField(label=_("allow_archive"), initial=None, required=False)
    baseurl = forms.CharField(label=_("baseurl"), initial=None, required=False)
    push_ssl = forms.ChoiceField(label=_("push_ssl"), required=False, choices=(('true', 'true'), ('false', 'false')))

    classes = {}

    def __init__(self, file_hash, *args, **kwargs):
        super(RepositoryForm, self).__init__(file_hash, *args, **kwargs)
        self.filtered_keys = self.fields.keys()
        # file hash field does not play in repository form logic.
        self.filtered_keys.remove('file_hash')

    def set_default(self, hgweb, hgrc):
        for field in self.filtered_keys:
            self.classes[field] = "r_val_default"
        if hgweb is not None:
            for field in self.filtered_keys:
                self._set_value(hgweb, field, "r_val_global")
        if hgrc is not None:
            for field in self.filtered_keys:
                self._set_value(hgrc, field, "r_val_local")

    def _set_value(self, conf, field_name, css_class):
        value = conf.get_web_key(field_name)
        if value is not None:
            if self.fields[field_name] is forms.BooleanField:
                if value == 'true':
                    self.fields[field_name].initial = 'true'
                else:
                    self.fields[field_name].initial = 'false'
            else:
                self.fields[field_name].initial = value
            self.classes[field_name] = css_class

    def export_values(self, hgrc, post):
        for field in self.filtered_keys:
            self._export_value(hgrc, field, post)

    def _export_value(self, hgrc, field_name, post):
        if field_name in post:
            hgrc.set_web_key(field_name, self.cleaned_data[field_name])


class AddUser(FileHashForm):
    login = forms.CharField(label=_("Login"), max_length=40, required=True)
    password1 = forms.CharField(label=_("Password"), max_length=20, required=True, widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Re-enter password"), max_length=20, required=True, widget=forms.PasswordInput)

    def __init__(self, file_hash, *args, **kwargs):
        super(AddUser, self).__init__(file_hash, *args, **kwargs)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(_("Passwords should be the same"))
        return password2

    def clean_login(self):
        login = self.cleaned_data["login"]
        if users.exists(settings.AUTH_FILE, login):
            raise forms.ValidationError(_("User exists"))
        return login


class EditUser(FileHashForm):
    password1 = forms.CharField(label=_("Password"), max_length=20, required=True, widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Re-enter password"), max_length=20, required=True, widget=forms.PasswordInput)

    def __init__(self, file_hash, *args, **kwargs):
        super(EditUser, self).__init__(file_hash, *args, **kwargs)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(_("Passwords should be the same"))
        return password2


class CreateRepoForm(FileHashForm):
    def __init__(self, default_groups, file_hash, *args, **kwargs):
        super(CreateRepoForm, self).__init__(file_hash, *args, **kwargs)
        self.fields['group'].choices = [("-", "-")] + default_groups

    def clean_name(self):
        _name = self.cleaned_data['name'].strip()
        if re.search(r"([\*:\?/\\]|^\.$|^\.\.$)", _name): #found one of (*:?/\) or . or ..
            raise forms.ValidationError(_("Don`t use special characters any of *:?/\ or names '.' and '..'"))
        return _name

    name = forms.CharField(label=_("Repository name"), max_length=100)
    group = forms.ChoiceField(label=_("Group"))

    def create_repository(self, request, groups):
        name = self.cleaned_data['name']
        group = self.cleaned_data['group']
        repo_path = prepare_path(name, group, groups)
        try:
            modhg.repository.create(repo_path, name, group == "-")
            messages.success(request, _("New repository was created."))
            if group == "-":
                redirect_path = reverse("repository", args=[name])
            else:
                redirect_path = reverse("repository", args=[group + os.path.sep + name])
        except modhg.repository.RepositoryException as e:
            messages.warning(request, unicode(e))
            return HttpResponseRedirect(reverse('index'))

        return HttpResponseRedirect(redirect_path)

    def rename(self, request, repo_path, groups, full_repository_path):
        name = self.cleaned_data['name']
        group = self.cleaned_data['group']
        new_path = prepare_path(name, group, groups)
        if new_path == full_repository_path:
            messages.warning(request,
                _("Repository '%(repo)s' was not moved to the same location: %(location)s.") % {
                    "repo": repo_path, "location": new_path})
            return HttpResponseRedirect(reverse("repository", args=[repo_path]))
        old_item_name = repo_path if group == "-" else ""
        try:
            repository.rename(full_repository_path, new_path, old_item_name, name)
            messages.success(request,
                _("Repository '%(old_path)s' moved by path '%(new_path)s' successfully.") % {
                    "old_path": full_repository_path,
                    "new_path": new_path})
            # eval new repo_path, might changed after 'repository.rename'.
            repo_path = "%s/%s" % (group, name) if group != "-" else name
            return HttpResponseRedirect(reverse("repository", args=[repo_path]))
        except RepositoryException as e:
            messages.warning(request,
                _("Repository '%(repo)s' was not moved: %(cause)s.") % {"repo": repo_path, "cause": unicode(e)})
            return HttpResponseRedirect(reverse("index"))


class ManageGroupsForm(FileHashForm):
    is_collection = forms.CharField(widget=forms.HiddenInput(), initial='False')
    name = forms.CharField(label=_("Group name"), max_length=100)
    path = forms.CharField(label=_("Path"))

    def __init__(self, file_hash, *args, **kwargs):
        super(ManageGroupsForm, self).__init__(file_hash, *args, **kwargs)

    def clean_path(self):
        _path = self.cleaned_data['path'].strip()
        if 'old_group_path' in self.data and _path == self.data['old_group_path']:
            return _path
        is_collection = self.cleaned_data.get('is_collection')
        if not is_collection == 'True' and not re.search(r"([/]\*{1,2})$", _path):
            raise forms.ValidationError(_("Path should be ended with /* or /**"))
        hgweb = HGWeb(settings.HGWEB_CONFIG)
        groups = hgweb.get_paths_and_collections()
        for name, path_item in groups:
            if path_item.rstrip('*/') == _path.rstrip('*/'):
                raise forms.ValidationError(_("The path is already defined by group: %s") % name)
        return _path


hgate/templates/base.html
{% load i18n %}
<html>
<head>
{% block head %}
    <script type="text/javascript" src="{{ MEDIA_URL }}/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}/js/jquery.treeview.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}/js/jquery.dimensions.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}/js/jquery.tooltip.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}/js/main.js"></script>

    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/css/main.css" />
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/css/jquery.treeview.css" />
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/css/jquery.tooltip.css" />
    <title>{% block title %}hGate{% endblock %}</title>


    <script>
        $(document).ready(function() {
            $("#repository_tree").treeview({
                persist: "location",
                collapsed: true
            });
            $("#menu_langs select").change(function() {
                $("#menu_langs").submit();
            });

            tooltip();
        });
    </script>
{% endblock %}
</head>
<body>
<div id="header" class="header">
    <h1 id="" class=""><a href="{% url index %}">hGate<sup>rc1</sup></a></h1>
    {% if hgweb_url != '-' %}
        <a style="position: relative; top: 60px; left: -85px;" class="external" href="{{ hgweb_url }}">hgweb</a>
    {% endif %}
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    <form action="{{ MEDIA_URL }}/i18n/setlang/" method="post" id="menu_langs">
        {% csrf_token %}
        <input name="next" type="hidden" value="."/>
        <select name="language">
            {% for lang in LANGUAGES %}
                <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %}selected{% endif %} >{{ lang.1 }}</option>
            {% endfor %}
        </select>
    </form>
    <ul id="menu_main_horizontal" class="">
        {% block menu_extra %}{% endblock %}
        <li class="{% block menu_home %}{% endblock %}"><a href="{% url index %}">{% trans "Home" %}</a></li>
        <li class="{% block menu_users %}{% endblock %}"><a href="{% url users_index %}">{% trans "Users" %}</a></li>
        <li class="{% block menu_hgweb %}{% endblock %}"><a href="{% url hgweb %}">{% trans "HgWeb" %}</a></li>
        <li class=""><a href="https://bitbucket.org/shedar/hgate/wiki/" target="_blank">{% trans "Help" %}</a></li>
    </ul>
</div>
{% block tree %}
<div class="tree">
{% include 'tree.html' %}
</div>
{% endblock %}
<div class="main">
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% trans message.message %}</li>
    {% endfor %}
</ul>
{% endif %}
{% block content %}
{% endblock %}
</div>
</body>
</html>

hgate/templates/errors.html
{% extends "base.html" %}
{% load i18n %}

{% block menu_home %}
    {% if menu == "home" %}current{% endif %}
{% endblock %}
{% block menu_users %}
    {% if menu == "users" %}current{% endif %}
{% endblock %}
{% block menu_extra %}
    {% if menu == "repository" %}
        {% if not global %}
            <li class="current"><a href="#">{% trans "Repository" %}</a></li>
        {% endif %}
    {% endif %}
{% endblock %}
{% block menu_hgweb %}
    {% if menu == "hgweb" %}current{% endif %}
{% endblock %}


{% block tree %}
{% endblock %}

{% block content %}
    <div class="text">
        <h1>
            .<br>
            / \<br>
            |<br>
            |<br>
            {% trans "Fix the above problem" %}<br>
            {% trans "to continue work!" %}
        </h1>
    </div>
{% endblock %}

hgate/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block menu_home %}current{% endblock %}
{% block head %}
    {{ block.super }}
    <script>
        var group_names = [{% for gr_key, gr_path in groups %}'{{ gr_key }}',{% endfor %}];
        var group_paths = [{% for gr_key, gr_path in groups %}'{{ gr_path }}',{% endfor %}];
        // regexp to match trailing /,/*,/**
        var replace = new RegExp("/\\*{0,2}$");

        function delete_group(name, path, reps_count, is_collection) {
            var do_delete = false;
            var delete_content = true;
            if (confirm("{% trans "Are you sure you want to delete group" %} '" + name + "'?")) {
                group_paths.forEach(function(element, index, array) {
                    if (element.replace(replace, "") == path.replace(replace, "") && name != group_names[index]) {
                        delete_content = confirm("{% trans "The path is already defined by group" %} '" + group_names[index] + "{% trans "', delete content of the group?" %}");
                        return 0;
                    }
                });
                if ((reps_count > 0) && delete_content) {
                    var repository_word = "{% trans "repositories" %}";
                    if (reps_count == 1)
                        repository_word = "{% trans "repository" %}";
                    if (confirm("{% trans "This group is not empty.\n It has " %} " + reps_count + " " + repository_word + ". {% trans "Delete anyway" %}?"))
                        do_delete = true;
                } else {
                    do_delete = true;
                }
            }
            if (do_delete) {
                $("#delete_group_form input[name='is_collection']").val(is_collection);
                $("#delete_group_form input[name='group_name']").val(name);
                $("#delete_group_form input[name='delete_content']").val(delete_content ? 'True' : 'False');
                $("#delete_group_form").submit();
            } else {
                $("#delete_group_form input[name='group_name']").val('');
            }
        }
        $(document).ready(function () {
            $("td.action span:first-child").click(function () {//edit
                $(this).nextAll().show();
                $(this).hide();
                var tdpath = $(this).parent().prev();
                var tdname = $(this).parent().prev().prev();
                var path = tdpath.html();
                var name = tdname.html();
                var path_width = tdpath.width();
                var name_width = tdname.width();
                tdpath.html('');
                $("<input type='text' value='" + path + "' />").filter("input")
                        .width(path_width)
//                        .keypress(function(e) {
//                            if(e.keyCode == 13) {
//                                todo commit by enter
//                            }
//                        })
                        .end().appendTo(tdpath);
                tdname.html('');
                $("<input type='text' value='" + name + "' />").filter("input")
                        .width(name_width)
                        .end().appendTo(tdname);

                $("<span>{% trans 'cancel' %}</span>").filter("span").click(
                        function () {
                            tdpath.html(path);
                            tdname.html(name);
                            $(this).prev().prev().show();
                            $(this).prev().remove();
                            $(this).remove();
                        }).end().insertAfter(this);
                $("<span style='padding-right:10pt;'>{% trans 'save' %}</span>").filter("span").click(
                        function () {
                            $("#old_group_name").val(name);
                            $("#old_group_path").val(path);
                            //getting td with collection
                            var is_collection = $(this).parent().prev().prev().prev().find("input").val();
                            //getting td with name
                            var new_name_val = $(this).parent().prev().prev().find("input").val();
                            //getting td with path
                            var new_path_val = $(this).parent().prev().find("input").val();
                            $("#id_edit_group-name").val(new_name_val);
                            $("#id_edit_group-path").val(new_path_val);
                            $("#id_edit_group-is_collection").val(is_collection);
                            $("#group_edit_form").submit();
                        }).end().insertAfter(this);
            });
            $(".group_list tbody tr").hover(
                    function () {
                        $(this).addClass("rowHover")
                    },
                    function () {
                        $(this).removeClass("rowHover");
                    }
            );
            $("#is_collection").click(function () {
                $("#id_is_collection").val(this.checked ? 'True' : 'False');
            });
            $("#is_collection").prop("checked", $("#id_is_collection").val() == 'True');
            function make_repo_summary() {
                var group = $("#id_group").val();
                var path = $("#id_group").find("option:selected").text();
                if (group == '-') {
                    group = '{% trans "No group" %}';
                    path = '{{ default_path }}';
                }
                var name = $("#id_name").val();
                path = path.replace(new RegExp("[*\/]+$", "g"), "") + "/";
                $("#repo_path_id").html(group + ": " + path + name);
            }
            $("#id_group").change(make_repo_summary);
            $("#id_name").keyup(make_repo_summary);
        });
    </script>
{% endblock %}

{% block content %}
    <br/>
    <h3>{% trans "Create repository" %}</h3>
    <form class="repository_create" action="{% url index %}" method="post">
        <table>
            {{ repo_form.as_table }}
            <tr>
                <td colspan="2" class="bottom">
                    <input class="submit" type="submit" name="create_repo" value="{% trans "Create" %}"/>
                    <span title="
                            {% blocktrans %} Create new repository : Path: default path ({{ default_path }}) if no group is specified or concrete group path.<br>Name: specified name.<br>This action creates dir with repository name and makes &apos;hg init&apos; in that dir. {% endblocktrans %}"
                          class="tooltip">[ ? ]</span>
                </td>
            </tr>
        </table>
    </form>
    <span style="font-size: small;" id="repo_path_id"></span>
    <hr style="margin: 15px 0 15px 0;"/>
    <h3>{% trans "Manage groups" %}</h3>

    <form class="group_create" id="group_create_id" action="{% url index %}" method="post">
        <table>
            {{ groups_form.as_table }}
            <tr>
                <th>
                    <label for="is_collection">{% trans "Collection" %}:</label>
                </th>
                <td align="left">
                    <input type="checkbox" id="is_collection" style="width: auto;"/>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="bottom">
                    <input class="submit" type="submit" name="create_group" value="{% trans "Create" %}"/>
                    <span title="{% trans 'Create new group : Creates all missing directories in the group path.<br>Adds record about this group to the hgweb.config.' %}"
                          class="tooltip">[ ? ]</span>
                </td>
            </tr>
        </table>
    </form>

    <form action="{% url index %}" id="delete_group_form" name="delete_group_form" method="post">
        {{ delete_group_form.non_field_errors }}
        {% for hidden in delete_group_form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <input type="hidden" name="group_name" value=""/>
        <input type="hidden" name="delete_group" value=""/>
        <input type="hidden" name="is_collection" value=""/>
        <input type="hidden" name="delete_content" value=""/>
    </form>
    <form id="group_edit_form" action="{% url index %}" style="display:none;" method="post">
        <input type="hidden" name="old_group_name" id="old_group_name" value=""/>
        <input type="hidden" name="old_group_path" id="old_group_path" value=""/>
        {{ edit_group_form.as_p }}
    </form>
    {{ edit_group_form.non_field_errors }}
    <table class="datagrid group_list">
        <tr>
            <th>{% trans "Type" %}</th>
            <th>{% trans "Group name" %}</th>
            <th>{% trans "Full path" %}</th>
            <th>{% trans "Action" %}</th>
        </tr>
        {% for gr_key, gr_path, rep_count, is_collection in groups %}
            <tr class="{% cycle odd,even %}">
                <td>
                    <input type="hidden" value="{{ is_collection }}"/>
                    {% if is_collection %}
                        [collections]
                    {% else %}
                        [paths]
                    {% endif %}
                </td>
                <td>{{ gr_key }}</td>
                <td>{{ gr_path }}</td>
                <td class="action">
                    <span title="{% trans 'Click to start editing this group: you can change name and path.' %}">
                        {% trans "edit" %}
                    </span>&nbsp;&nbsp;
                    <span class="delete_group"
                          onclick="delete_group('{{ gr_key }}', '{{ gr_path }}', '{{ rep_count }}', '{{ is_collection }}');"
                          title="{% trans 'Delete the group: removes record about this group from hgweb.config. Deletes group`s dir and all it`s subdirectories.' %}">
                         {% trans "delete" %}
                    </span>
                    {% if gr_key == old_group_name and gr_path == old_group_path %}
                        <div id="error_here">
                            <script type="text/javascript">
                                $(document).ready(function () {
                                    $("#error_here").prev().prev().click();
                                    var td_path_html = $("#error_here").parent().prev().html();
                                    var td_name_html = $("#error_here").parent().prev().prev().html();

                                    td_path_html = td_path_html.replace("{{ old_group_path }}", $('{{ edit_group_form.path }}').val());
                                    td_name_html = td_name_html.replace("{{ old_group_name }}", $('{{ edit_group_form.name }}').val());

                                    $("#error_here").parent().prev().html('{{ edit_group_form.path.errors|escape }}' + td_path_html);
                                    $("#error_here").parent().prev().prev().html('{{ edit_group_form.name.errors|escape }}' + td_name_html);
                                    $("#error_here").remove();
                                });
                            </script>
                        </div>
                    {% endif %}
                </td>
            </tr>
        {% empty %}
            <tr><td colspan="4" align="center"><em>{% trans "There are no groups." %}</em></td></tr>
        {% endfor %}
    </table>

{% endblock %}

hgate/templates/tree.html
<ul id="repository_tree">{{ tree|safe }}</ul>

hgate/templates/useredit.html
{% extends "base.html" %}
{% load i18n %}

{% block menu_users %}current{% endblock %}
{% block head %}
{{ block.super }}
<script>
 $(document).ready(function(){
    $(".permission_table tbody tr").hover(
        function(){$(this).addClass("rowHover")},
        function(){$(this).removeClass("rowHover");}
     );
  })
</script>
{% endblock %}

{% block content %}
<a class="back" href="{% url users_index %}">{% trans "<< Back to users list" %}</a><br />
<h2>{% trans "User" %}: {{ login }}</h2>
<h3>{% trans "Change password" %}</h3>
<form class="user_edit" action="{% url users "edit" login %}" method="post">
    <table>
        {{ form.as_table }}
        <tr><td colspan="2" class="bottom">
          <input class="submit" type="submit" value="{% trans "Save" %}" />
          <span title="{% trans 'Change passwrod : Modifies users file, changes password for the user.' %}" class="tooltip">[ ? ]</span>
        </td></tr>
    </table>
    
</form>

<h3>{% trans "Permissions" %}</h3>
<table class="datagrid permission_table">
<tr>
    <th class="th_repository">{% trans "Repository" %}</th>
    <th class="td_perm">
        <div class="fll">{% trans "Read" %}</div><div class="flr">{% trans "Push" %}</div><div>/</div>
    </th>
</tr>
{% for repository, perm in permissions.items %}
    <tr class="{% cycle odd,even %}">
        <td>{{ repository }}</td>
        <td class="td_perm">
            <div class="fll">{{ perm.read }}</div><div class="flr">{{ perm.push }}</div><div>/</div>
        </td>
    </tr>
{% empty %}
    <tr><td colspan="2" align="center"><em>{% trans "User does not have any permissions." %}</em></td></tr>
{% endfor %}
</table>

{% endblock %}

hgate/templates/users.html
{% extends "base.html" %}
{% load i18n %}

{% block menu_users %}current{% endblock %}
{% block head %}
{{ block.super }}
<script>
 $(document).ready(function(){
    $(".user_list tbody tr").hover(
        function(){$(this).addClass("rowHover")},
        function(){$(this).removeClass("rowHover");}
     );
    $(".user_delete").click(function(){
        var login = $(this).parents("tr").find("td.login").text();
        if (confirm("{% trans "Delete user" %} '"+login+"'?")) {
            $("#delete_user_form input[name='login']").val(login);
            $("#delete_user_form").submit();
        }
    });
  })
</script>
{% endblock %}

{% block content %}
<h3>{% trans "Create user" %}</h3>
<form class="user_create" action="{% url users_index %}" method="post">
    <table>
        {{ form.as_table }}
    <tr><td colspan="2" class="bottom">
        <input class="submit" type="submit" name="add_user" value="{% trans "Create" %}" />
        <span title="{% trans 'Add new user : Modifies users file, adds line user_name:crypted_password.' %}" class="tooltip">[ ? ]</span>
    </td></tr>
    </table>
</form>
<h3>{% trans "Manage users" %}</h3>
<form action="{% url users_index %}" id="delete_user_form" name="delete_user_form" method="post">
    {{ delete_user_form.non_field_errors }}
    {% for hidden in delete_user_form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    <input type="hidden" name="login" value=""/>
    <input type="hidden" name="delete_user" value=""/>
</form>
<table class="datagrid user_list">
<tr><th>{% trans "Login" %}</th><th>{% trans "Action" %}</th></tr>
{% for user in users %}
<tr class="{% cycle odd,even %}">
    <td class="login">{{ user }}</td>
    <td class="action"><a href="{% url users "edit" user %}"
           title="{% trans "Change password and manage user's permissions" %}">{% trans "edit" %}</a>&nbsp;&nbsp;
        <span class="user_delete" title="{% trans "Remove user" %}">{% trans "delete" %}</span>
    </td>
{% empty %}
    <tr><td colspan="2" align="center"><em>{% trans "There are no users." %}</em></td></tr>
{% endfor %}
</table>
{% endblock %}